/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace Hero.Message.Auto
{
  public static class MessageTypeConstants
  {
	public static int CS_REGISTER = 100001;
	public static int CS_LOGIN = 100002;
    public static int CS_CREATE_NEW_CHAR = 100003;
    public static int CS_QUERY_CHARACTER_INFO = 100004;
    public static int CS_PING = 100005;
    public static int CS_RANDOM_NAME = 100006;
    public static int CS_QUERY_MAIL_LIST = 101001;
    public static int CS_MARK_MAIL = 101002;
    public static int SC_REGISTER = 200001;
    public static int SC_LOGIN = 200002;
    public static int SC_NOTICE_CREATE_NEW_CHAR = 200003;
    public static int SC_CREATE_NEW_CHAR = 200004;
    public static int SC_SYSTEM_INFO = 200005;
    public static int SC_CHARACTER_INFO = 200006;
    public static int SC_PING = 200007;
    public static int SC_RANDOM_NAME = 200008;
    public static int SC_QUERY_MAIL_LIST = 201001;
    public static int SC_NEW_MAIL = 201002;
  }
}
