/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Message.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCNewMailMsg : TBase
  {
    private Hero.Message.Auto.MailInfo _mailInfo;

    public Hero.Message.Auto.MailInfo MailInfo
    {
      get
      {
        return _mailInfo;
      }
      set
      {
        __isset.mailInfo = true;
        this._mailInfo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool mailInfo;
    }

    public SCNewMailMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Struct) {
              MailInfo = new Hero.Message.Auto.MailInfo();
              MailInfo.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCNewMailMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MailInfo != null && __isset.mailInfo) {
        field.Name = "mailInfo";
        field.Type = TType.Struct;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        MailInfo.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCNewMailMsg(");
      sb.Append("MailInfo: ");
      sb.Append(MailInfo== null ? "<null>" : MailInfo.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
