/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Message.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCQueryMailListMsg : TBase
  {
    private List<Hero.Message.Auto.MailInfo> _mailInfoList;

    public List<Hero.Message.Auto.MailInfo> MailInfoList
    {
      get
      {
        return _mailInfoList;
      }
      set
      {
        __isset.mailInfoList = true;
        this._mailInfoList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool mailInfoList;
    }

    public SCQueryMailListMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.List) {
              {
                MailInfoList = new List<Hero.Message.Auto.MailInfo>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  Hero.Message.Auto.MailInfo _elem2 = new Hero.Message.Auto.MailInfo();
                  _elem2 = new Hero.Message.Auto.MailInfo();
                  _elem2.Read(iprot);
                  MailInfoList.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCQueryMailListMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MailInfoList != null && __isset.mailInfoList) {
        field.Name = "mailInfoList";
        field.Type = TType.List;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, MailInfoList.Count));
          foreach (Hero.Message.Auto.MailInfo _iter3 in MailInfoList)
          {
            _iter3.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCQueryMailListMsg(");
      sb.Append("MailInfoList: ");
      sb.Append(MailInfoList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
