/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace Hero.Message.Auto
{
  public static class TipMessageIdConstants
  {
    public static int FORCE_KICK = 10000;
    public static int USER_PASSWORD_ERROR = 10001;
    public static int CHAR_NAME_LEN_INVALID = 10002;
    public static int CHAR_NAME_INVALID = 10003;
    public static int DUPLICATE_CHAR_NAME = 10004;
    public static int SERVER_NOT_OPEN = 10005;
    public static int USER_LOCKED = 10006;
    public static int SERVER_BUSY = 10007;
    public static int SERVER_ONLINE_PLAYER_FULL = 10008;
    public static int AUTH_CHANNEL_CODE_NOT_SUPPORT = 10009;
  }
}
