/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CharacterLevelsConfig : TBase
  {
    private Dictionary<short, CharacterLevelConfig> _levelMap;

    public Dictionary<short, CharacterLevelConfig> LevelMap
    {
      get
      {
        return _levelMap;
      }
      set
      {
        __isset.levelMap = true;
        this._levelMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool levelMap;
    }

    public CharacterLevelsConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                LevelMap = new Dictionary<short, CharacterLevelConfig>();
                TMap _map94 = iprot.ReadMapBegin();
                for( int _i95 = 0; _i95 < _map94.Count; ++_i95)
                {
                  short _key96;
                  CharacterLevelConfig _val97;
                  _key96 = iprot.ReadI16();
                  _val97 = new CharacterLevelConfig();
                  _val97.Read(iprot);
                  LevelMap[_key96] = _val97;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CharacterLevelsConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (LevelMap != null && __isset.levelMap) {
        field.Name = "levelMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I16, TType.Struct, LevelMap.Count));
          foreach (short _iter98 in LevelMap.Keys)
          {
            oprot.WriteI16(_iter98);
            LevelMap[_iter98].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CharacterLevelsConfig(");
      sb.Append("LevelMap: ");
      sb.Append(LevelMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
