/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ExchangesConfig : TBase
  {
    private Dictionary<int, ExchangeConfig> _exchangeConfigMap;

    public Dictionary<int, ExchangeConfig> ExchangeConfigMap
    {
      get
      {
        return _exchangeConfigMap;
      }
      set
      {
        __isset.exchangeConfigMap = true;
        this._exchangeConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool exchangeConfigMap;
    }

    public ExchangesConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ExchangeConfigMap = new Dictionary<int, ExchangeConfig>();
                TMap _map89 = iprot.ReadMapBegin();
                for( int _i90 = 0; _i90 < _map89.Count; ++_i90)
                {
                  int _key91;
                  ExchangeConfig _val92;
                  _key91 = iprot.ReadI32();
                  _val92 = new ExchangeConfig();
                  _val92.Read(iprot);
                  ExchangeConfigMap[_key91] = _val92;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ExchangesConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ExchangeConfigMap != null && __isset.exchangeConfigMap) {
        field.Name = "exchangeConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ExchangeConfigMap.Count));
          foreach (int _iter93 in ExchangeConfigMap.Keys)
          {
            oprot.WriteI32(_iter93);
            ExchangeConfigMap[_iter93].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ExchangesConfig(");
      sb.Append("ExchangeConfigMap: ");
      sb.Append(ExchangeConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
