/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class FuncConfig : TBase
  {
    private Dictionary<int, FuncGroup> _funcMap;

    public Dictionary<int, FuncGroup> FuncMap
    {
      get
      {
        return _funcMap;
      }
      set
      {
        __isset.funcMap = true;
        this._funcMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool funcMap;
    }

    public FuncConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                FuncMap = new Dictionary<int, FuncGroup>();
                TMap _map62 = iprot.ReadMapBegin();
                for( int _i63 = 0; _i63 < _map62.Count; ++_i63)
                {
                  int _key64;
                  FuncGroup _val65;
                  _key64 = iprot.ReadI32();
                  _val65 = new FuncGroup();
                  _val65.Read(iprot);
                  FuncMap[_key64] = _val65;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("FuncConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (FuncMap != null && __isset.funcMap) {
        field.Name = "funcMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, FuncMap.Count));
          foreach (int _iter66 in FuncMap.Keys)
          {
            oprot.WriteI32(_iter66);
            FuncMap[_iter66].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("FuncConfig(");
      sb.Append("FuncMap: ");
      sb.Append(FuncMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
