/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class HeroConfig : TBase
  {
    private int _itemId;
    private int _groupId;
    private int _heroNameMessageId;
    private int _heroDescMessageId;
    private sbyte _quality;
    private sbyte _star;
    private sbyte _initLevel;
    private short _initAtt;
    private int _addAtt;
    private short _initDef;
    private int _addDef;
    private short _initHp;
    private int _addHp;
    private short _initLuck;
    private int _addLuck;
    private int _initSkillId;
    private string _icon;
    private sbyte _mode;
    private sbyte _camp;
    private int _decompExp;
    private int _advanceCostGold;
    private sbyte _decompSoulMin;
    private sbyte _decompSoulMax;

    public int ItemId
    {
      get
      {
        return _itemId;
      }
      set
      {
        __isset.itemId = true;
        this._itemId = value;
      }
    }

    public int GroupId
    {
      get
      {
        return _groupId;
      }
      set
      {
        __isset.groupId = true;
        this._groupId = value;
      }
    }

    public int HeroNameMessageId
    {
      get
      {
        return _heroNameMessageId;
      }
      set
      {
        __isset.heroNameMessageId = true;
        this._heroNameMessageId = value;
      }
    }

    public int HeroDescMessageId
    {
      get
      {
        return _heroDescMessageId;
      }
      set
      {
        __isset.heroDescMessageId = true;
        this._heroDescMessageId = value;
      }
    }

    public sbyte Quality
    {
      get
      {
        return _quality;
      }
      set
      {
        __isset.quality = true;
        this._quality = value;
      }
    }

    public sbyte Star
    {
      get
      {
        return _star;
      }
      set
      {
        __isset.star = true;
        this._star = value;
      }
    }

    public sbyte InitLevel
    {
      get
      {
        return _initLevel;
      }
      set
      {
        __isset.initLevel = true;
        this._initLevel = value;
      }
    }

    public short InitAtt
    {
      get
      {
        return _initAtt;
      }
      set
      {
        __isset.initAtt = true;
        this._initAtt = value;
      }
    }

    public int AddAtt
    {
      get
      {
        return _addAtt;
      }
      set
      {
        __isset.addAtt = true;
        this._addAtt = value;
      }
    }

    public short InitDef
    {
      get
      {
        return _initDef;
      }
      set
      {
        __isset.initDef = true;
        this._initDef = value;
      }
    }

    public int AddDef
    {
      get
      {
        return _addDef;
      }
      set
      {
        __isset.addDef = true;
        this._addDef = value;
      }
    }

    public short InitHp
    {
      get
      {
        return _initHp;
      }
      set
      {
        __isset.initHp = true;
        this._initHp = value;
      }
    }

    public int AddHp
    {
      get
      {
        return _addHp;
      }
      set
      {
        __isset.addHp = true;
        this._addHp = value;
      }
    }

    public short InitLuck
    {
      get
      {
        return _initLuck;
      }
      set
      {
        __isset.initLuck = true;
        this._initLuck = value;
      }
    }

    public int AddLuck
    {
      get
      {
        return _addLuck;
      }
      set
      {
        __isset.addLuck = true;
        this._addLuck = value;
      }
    }

    public int InitSkillId
    {
      get
      {
        return _initSkillId;
      }
      set
      {
        __isset.initSkillId = true;
        this._initSkillId = value;
      }
    }

    public string Icon
    {
      get
      {
        return _icon;
      }
      set
      {
        __isset.icon = true;
        this._icon = value;
      }
    }

    public sbyte Mode
    {
      get
      {
        return _mode;
      }
      set
      {
        __isset.mode = true;
        this._mode = value;
      }
    }

    public sbyte Camp
    {
      get
      {
        return _camp;
      }
      set
      {
        __isset.camp = true;
        this._camp = value;
      }
    }

    public int DecompExp
    {
      get
      {
        return _decompExp;
      }
      set
      {
        __isset.decompExp = true;
        this._decompExp = value;
      }
    }

    public int AdvanceCostGold
    {
      get
      {
        return _advanceCostGold;
      }
      set
      {
        __isset.advanceCostGold = true;
        this._advanceCostGold = value;
      }
    }

    public sbyte DecompSoulMin
    {
      get
      {
        return _decompSoulMin;
      }
      set
      {
        __isset.decompSoulMin = true;
        this._decompSoulMin = value;
      }
    }

    public sbyte DecompSoulMax
    {
      get
      {
        return _decompSoulMax;
      }
      set
      {
        __isset.decompSoulMax = true;
        this._decompSoulMax = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool itemId;
      public bool groupId;
      public bool heroNameMessageId;
      public bool heroDescMessageId;
      public bool quality;
      public bool star;
      public bool initLevel;
      public bool initAtt;
      public bool addAtt;
      public bool initDef;
      public bool addDef;
      public bool initHp;
      public bool addHp;
      public bool initLuck;
      public bool addLuck;
      public bool initSkillId;
      public bool icon;
      public bool mode;
      public bool camp;
      public bool decompExp;
      public bool advanceCostGold;
      public bool decompSoulMin;
      public bool decompSoulMax;
    }

    public HeroConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              ItemId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              GroupId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.I32) {
              HeroNameMessageId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 40:
            if (field.Type == TType.I32) {
              HeroDescMessageId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 50:
            if (field.Type == TType.Byte) {
              Quality = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 60:
            if (field.Type == TType.Byte) {
              Star = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 70:
            if (field.Type == TType.Byte) {
              InitLevel = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 80:
            if (field.Type == TType.I16) {
              InitAtt = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 90:
            if (field.Type == TType.I32) {
              AddAtt = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 100:
            if (field.Type == TType.I16) {
              InitDef = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 110:
            if (field.Type == TType.I32) {
              AddDef = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 120:
            if (field.Type == TType.I16) {
              InitHp = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 130:
            if (field.Type == TType.I32) {
              AddHp = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 140:
            if (field.Type == TType.I16) {
              InitLuck = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 150:
            if (field.Type == TType.I32) {
              AddLuck = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 160:
            if (field.Type == TType.I32) {
              InitSkillId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 170:
            if (field.Type == TType.String) {
              Icon = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 180:
            if (field.Type == TType.Byte) {
              Mode = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 190:
            if (field.Type == TType.Byte) {
              Camp = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 200:
            if (field.Type == TType.I32) {
              DecompExp = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 210:
            if (field.Type == TType.I32) {
              AdvanceCostGold = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 220:
            if (field.Type == TType.Byte) {
              DecompSoulMin = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 230:
            if (field.Type == TType.Byte) {
              DecompSoulMax = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("HeroConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.itemId) {
        field.Name = "itemId";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ItemId);
        oprot.WriteFieldEnd();
      }
      if (__isset.groupId) {
        field.Name = "groupId";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(GroupId);
        oprot.WriteFieldEnd();
      }
      if (__isset.heroNameMessageId) {
        field.Name = "heroNameMessageId";
        field.Type = TType.I32;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(HeroNameMessageId);
        oprot.WriteFieldEnd();
      }
      if (__isset.heroDescMessageId) {
        field.Name = "heroDescMessageId";
        field.Type = TType.I32;
        field.ID = 40;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(HeroDescMessageId);
        oprot.WriteFieldEnd();
      }
      if (__isset.quality) {
        field.Name = "quality";
        field.Type = TType.Byte;
        field.ID = 50;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Quality);
        oprot.WriteFieldEnd();
      }
      if (__isset.star) {
        field.Name = "star";
        field.Type = TType.Byte;
        field.ID = 60;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Star);
        oprot.WriteFieldEnd();
      }
      if (__isset.initLevel) {
        field.Name = "initLevel";
        field.Type = TType.Byte;
        field.ID = 70;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(InitLevel);
        oprot.WriteFieldEnd();
      }
      if (__isset.initAtt) {
        field.Name = "initAtt";
        field.Type = TType.I16;
        field.ID = 80;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(InitAtt);
        oprot.WriteFieldEnd();
      }
      if (__isset.addAtt) {
        field.Name = "addAtt";
        field.Type = TType.I32;
        field.ID = 90;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AddAtt);
        oprot.WriteFieldEnd();
      }
      if (__isset.initDef) {
        field.Name = "initDef";
        field.Type = TType.I16;
        field.ID = 100;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(InitDef);
        oprot.WriteFieldEnd();
      }
      if (__isset.addDef) {
        field.Name = "addDef";
        field.Type = TType.I32;
        field.ID = 110;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AddDef);
        oprot.WriteFieldEnd();
      }
      if (__isset.initHp) {
        field.Name = "initHp";
        field.Type = TType.I16;
        field.ID = 120;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(InitHp);
        oprot.WriteFieldEnd();
      }
      if (__isset.addHp) {
        field.Name = "addHp";
        field.Type = TType.I32;
        field.ID = 130;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AddHp);
        oprot.WriteFieldEnd();
      }
      if (__isset.initLuck) {
        field.Name = "initLuck";
        field.Type = TType.I16;
        field.ID = 140;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(InitLuck);
        oprot.WriteFieldEnd();
      }
      if (__isset.addLuck) {
        field.Name = "addLuck";
        field.Type = TType.I32;
        field.ID = 150;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AddLuck);
        oprot.WriteFieldEnd();
      }
      if (__isset.initSkillId) {
        field.Name = "initSkillId";
        field.Type = TType.I32;
        field.ID = 160;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(InitSkillId);
        oprot.WriteFieldEnd();
      }
      if (Icon != null && __isset.icon) {
        field.Name = "icon";
        field.Type = TType.String;
        field.ID = 170;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Icon);
        oprot.WriteFieldEnd();
      }
      if (__isset.mode) {
        field.Name = "mode";
        field.Type = TType.Byte;
        field.ID = 180;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Mode);
        oprot.WriteFieldEnd();
      }
      if (__isset.camp) {
        field.Name = "camp";
        field.Type = TType.Byte;
        field.ID = 190;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Camp);
        oprot.WriteFieldEnd();
      }
      if (__isset.decompExp) {
        field.Name = "decompExp";
        field.Type = TType.I32;
        field.ID = 200;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DecompExp);
        oprot.WriteFieldEnd();
      }
      if (__isset.advanceCostGold) {
        field.Name = "advanceCostGold";
        field.Type = TType.I32;
        field.ID = 210;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AdvanceCostGold);
        oprot.WriteFieldEnd();
      }
      if (__isset.decompSoulMin) {
        field.Name = "decompSoulMin";
        field.Type = TType.Byte;
        field.ID = 220;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(DecompSoulMin);
        oprot.WriteFieldEnd();
      }
      if (__isset.decompSoulMax) {
        field.Name = "decompSoulMax";
        field.Type = TType.Byte;
        field.ID = 230;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(DecompSoulMax);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("HeroConfig(");
      sb.Append("ItemId: ");
      sb.Append(ItemId);
      sb.Append(",GroupId: ");
      sb.Append(GroupId);
      sb.Append(",HeroNameMessageId: ");
      sb.Append(HeroNameMessageId);
      sb.Append(",HeroDescMessageId: ");
      sb.Append(HeroDescMessageId);
      sb.Append(",Quality: ");
      sb.Append(Quality);
      sb.Append(",Star: ");
      sb.Append(Star);
      sb.Append(",InitLevel: ");
      sb.Append(InitLevel);
      sb.Append(",InitAtt: ");
      sb.Append(InitAtt);
      sb.Append(",AddAtt: ");
      sb.Append(AddAtt);
      sb.Append(",InitDef: ");
      sb.Append(InitDef);
      sb.Append(",AddDef: ");
      sb.Append(AddDef);
      sb.Append(",InitHp: ");
      sb.Append(InitHp);
      sb.Append(",AddHp: ");
      sb.Append(AddHp);
      sb.Append(",InitLuck: ");
      sb.Append(InitLuck);
      sb.Append(",AddLuck: ");
      sb.Append(AddLuck);
      sb.Append(",InitSkillId: ");
      sb.Append(InitSkillId);
      sb.Append(",Icon: ");
      sb.Append(Icon);
      sb.Append(",Mode: ");
      sb.Append(Mode);
      sb.Append(",Camp: ");
      sb.Append(Camp);
      sb.Append(",DecompExp: ");
      sb.Append(DecompExp);
      sb.Append(",AdvanceCostGold: ");
      sb.Append(AdvanceCostGold);
      sb.Append(",DecompSoulMin: ");
      sb.Append(DecompSoulMin);
      sb.Append(",DecompSoulMax: ");
      sb.Append(DecompSoulMax);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
