/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class HerosConfig : TBase
  {
    private Dictionary<int, HeroConfig> _cardConfigMap;

    public Dictionary<int, HeroConfig> CardConfigMap
    {
      get
      {
        return _cardConfigMap;
      }
      set
      {
        __isset.cardConfigMap = true;
        this._cardConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool cardConfigMap;
    }

    public HerosConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                CardConfigMap = new Dictionary<int, HeroConfig>();
                TMap _map5 = iprot.ReadMapBegin();
                for( int _i6 = 0; _i6 < _map5.Count; ++_i6)
                {
                  int _key7;
                  HeroConfig _val8;
                  _key7 = iprot.ReadI32();
                  _val8 = new HeroConfig();
                  _val8.Read(iprot);
                  CardConfigMap[_key7] = _val8;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("HerosConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CardConfigMap != null && __isset.cardConfigMap) {
        field.Name = "cardConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, CardConfigMap.Count));
          foreach (int _iter9 in CardConfigMap.Keys)
          {
            oprot.WriteI32(_iter9);
            CardConfigMap[_iter9].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("HerosConfig(");
      sb.Append("CardConfigMap: ");
      sb.Append(CardConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
