/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class LimitFuncScenesConfig : TBase
  {
    private Dictionary<int, LimitFuncSceneConfig> _scenenConfigMap;

    public Dictionary<int, LimitFuncSceneConfig> ScenenConfigMap
    {
      get
      {
        return _scenenConfigMap;
      }
      set
      {
        __isset.scenenConfigMap = true;
        this._scenenConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool scenenConfigMap;
    }

    public LimitFuncScenesConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ScenenConfigMap = new Dictionary<int, LimitFuncSceneConfig>();
                TMap _map71 = iprot.ReadMapBegin();
                for( int _i72 = 0; _i72 < _map71.Count; ++_i72)
                {
                  int _key73;
                  LimitFuncSceneConfig _val74;
                  _key73 = iprot.ReadI32();
                  _val74 = new LimitFuncSceneConfig();
                  _val74.Read(iprot);
                  ScenenConfigMap[_key73] = _val74;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LimitFuncScenesConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ScenenConfigMap != null && __isset.scenenConfigMap) {
        field.Name = "scenenConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ScenenConfigMap.Count));
          foreach (int _iter75 in ScenenConfigMap.Keys)
          {
            oprot.WriteI32(_iter75);
            ScenenConfigMap[_iter75].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LimitFuncScenesConfig(");
      sb.Append("ScenenConfigMap: ");
      sb.Append(ScenenConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
