/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class LimitConfg : TBase
  {
    private Dictionary<int, LimitGroup> _limitMap;

    public Dictionary<int, LimitGroup> LimitMap
    {
      get
      {
        return _limitMap;
      }
      set
      {
        __isset.limitMap = true;
        this._limitMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool limitMap;
    }

    public LimitConfg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                LimitMap = new Dictionary<int, LimitGroup>();
                TMap _map45 = iprot.ReadMapBegin();
                for( int _i46 = 0; _i46 < _map45.Count; ++_i46)
                {
                  int _key47;
                  LimitGroup _val48;
                  _key47 = iprot.ReadI32();
                  _val48 = new LimitGroup();
                  _val48.Read(iprot);
                  LimitMap[_key47] = _val48;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LimitConfg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (LimitMap != null && __isset.limitMap) {
        field.Name = "limitMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, LimitMap.Count));
          foreach (int _iter49 in LimitMap.Keys)
          {
            oprot.WriteI32(_iter49);
            LimitMap[_iter49].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LimitConfg(");
      sb.Append("LimitMap: ");
      sb.Append(LimitMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
