/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class LimitFuncSceneConfig : TBase
  {
    private int _sceneId;
    private List<LimitFuncScene> _sceneList;

    public int SceneId
    {
      get
      {
        return _sceneId;
      }
      set
      {
        __isset.sceneId = true;
        this._sceneId = value;
      }
    }

    public List<LimitFuncScene> SceneList
    {
      get
      {
        return _sceneList;
      }
      set
      {
        __isset.sceneList = true;
        this._sceneList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool sceneId;
      public bool sceneList;
    }

    public LimitFuncSceneConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              SceneId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                SceneList = new List<LimitFuncScene>();
                TList _list67 = iprot.ReadListBegin();
                for( int _i68 = 0; _i68 < _list67.Count; ++_i68)
                {
                  LimitFuncScene _elem69 = new LimitFuncScene();
                  _elem69 = new LimitFuncScene();
                  _elem69.Read(iprot);
                  SceneList.Add(_elem69);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LimitFuncSceneConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.sceneId) {
        field.Name = "sceneId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SceneId);
        oprot.WriteFieldEnd();
      }
      if (SceneList != null && __isset.sceneList) {
        field.Name = "sceneList";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, SceneList.Count));
          foreach (LimitFuncScene _iter70 in SceneList)
          {
            _iter70.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LimitFuncSceneConfig(");
      sb.Append("SceneId: ");
      sb.Append(SceneId);
      sb.Append(",SceneList: ");
      sb.Append(SceneList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
