/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hero.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MessageConfig : TBase
  {
    private Dictionary<string, Dictionary<int, string>> _messageMap;

    public Dictionary<string, Dictionary<int, string>> MessageMap
    {
      get
      {
        return _messageMap;
      }
      set
      {
        __isset.messageMap = true;
        this._messageMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool messageMap;
    }

    public MessageConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                MessageMap = new Dictionary<string, Dictionary<int, string>>();
                TMap _map67 = iprot.ReadMapBegin();
                for( int _i68 = 0; _i68 < _map67.Count; ++_i68)
                {
                  string _key69;
                  Dictionary<int, string> _val70;
                  _key69 = iprot.ReadString();
                  {
                    _val70 = new Dictionary<int, string>();
                    TMap _map71 = iprot.ReadMapBegin();
                    for( int _i72 = 0; _i72 < _map71.Count; ++_i72)
                    {
                      int _key73;
                      string _val74;
                      _key73 = iprot.ReadI32();
                      _val74 = iprot.ReadString();
                      _val70[_key73] = _val74;
                    }
                    iprot.ReadMapEnd();
                  }
                  MessageMap[_key69] = _val70;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MessageConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MessageMap != null && __isset.messageMap) {
        field.Name = "messageMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.Map, MessageMap.Count));
          foreach (string _iter75 in MessageMap.Keys)
          {
            oprot.WriteString(_iter75);
            {
              oprot.WriteMapBegin(new TMap(TType.I32, TType.String, MessageMap[_iter75].Count));
              foreach (int _iter76 in MessageMap[_iter75].Keys)
              {
                oprot.WriteI32(_iter76);
                oprot.WriteString(MessageMap[_iter75][_iter76]);
              }
              oprot.WriteMapEnd();
            }
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MessageConfig(");
      sb.Append("MessageMap: ");
      sb.Append(MessageMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
