// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Battle;

public interface IAIContext
{
//    void setParam(Dictionary<string,object> param);
//
//    object getValueOfKeyWithDefault(string key, object value = null);
//
//    void ModifyOrAddValueOfNotExsitKey(string key, object value);
//
//    void DeletParamOfKey(string key);

    object Agent { get;}
}


